day26 Initial commit
PS C:\Users\sinem\OneDrive\Pictures\BTI\addis-cafe--> git pull origin main --rebase
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
rOAemote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 872 bytes | 58.00 KiB/s, done.
From https://github.com/sinemistermekonen-web/Frontend-react-and-Next.js
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: could not apply 3d9a0f7... day26 Initial commit
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 3d9a0f7... # day26 Initial commit
PS C:\Users\sinem\OneDrive\Pictures\BTI\addis-cafe-->  # with '#' will be ignored, and an empty message aborts the commit.
g#	new file:   src/App.jsx
#